### ISSUE TITLE
Fat Fuck Run '91

### ISSUE THREAD

**Issue by wetchicken** [SuperFLEB/blender_convert_mapping_node#1]
Sorry for contacting you this way, but it's the only method I have found so far.
Is this your project? http://pixelsaredead.com/cabletv/ I was mesmerized as a kid staring at the one on the local cable company, and then one day I didn't think it could get better... they were editing the pages right on the screen! LOL
Anyway, I am wondering how far you are along in your project, as I would like to run one. I hardly know any code, so I apologize that I can't help develop it.

**Comment by SuperFLEB** [comment]
Sorry to disappoint, but that really didn't go anywhere. My personal websites have been pretty well neglected due to work and other personal projects, so I haven't picked that up in years. I'll see if I can package it up and at least get it onto GitHub sometime here, and let you know when I do.

**Comment by n1iic** [comment]
That would be appreciated! Thank you. I understand the life before projects issue,I have a house full of unfinished ones.

**Comment by SuperFLEB** [comment]
The Fat Fuck Fun Run '91 is on! (Well, actually, I swapped out a bunch of the text, so that's not there any more.)

Check out https://github.com/SuperFLEB/cable_tv . I did kind of drag the code back into respectability a bit. It uses vanilla JavaScript, now, and I added blinking! I also tuned up that bottom scroll to a new, less JavaScript-y, less overall janky version I was working on. That said, that added its own pile of jank, and, well, it's serviceable, but it could use some work.

You'll have to bring your own fonts (instructions are in the README). I don't know what the license is on the ones I used, so I didn't feel comfortable including them. That said, they're a download away.
